"""UUID v7 primary keys (Conventions §3).

Every primary key in CollabHub is a time-ordered UUID v7 generated by the
application, not the database, because IDs must be known before insert — a
message's ID goes into the job envelope and the Socket.IO broadcast, both of
which happen around the write rather than after it.

Python 3.12's `uuid` module has no `uuid7` (it lands in 3.14), so this is a
direct implementation of RFC 9562 §5.7 with the "replace leftmost random bits
with an increased clock precision" monotonicity guarantee (§6.2, method 2): the
12-bit `rand_a` field is used as a counter so IDs minted inside the same
millisecond still sort in generation order.
"""

from __future__ import annotations

import secrets
import threading
import time
import uuid

_COUNTER_BITS = 12
_COUNTER_MAX = (1 << _COUNTER_BITS) - 1

# Seed the counter well below its ceiling so a burst inside one millisecond has
# room to increment without borrowing from the next millisecond.
_COUNTER_SEED_MAX = _COUNTER_MAX >> 1

_lock = threading.Lock()
_last_ms = 0
_counter = 0


def uuid7() -> uuid.UUID:
    """Return a time-ordered UUID v7.

    Monotonic across calls even within a millisecond, and never goes backwards
    if the system clock does.
    """
    global _last_ms, _counter

    with _lock:
        now_ms = time.time_ns() // 1_000_000

        if now_ms > _last_ms:
            _last_ms = now_ms
            _counter = secrets.randbelow(_COUNTER_SEED_MAX + 1)
        elif _counter >= _COUNTER_MAX:
            # Out of counter space in this millisecond: borrow the next one
            # rather than block. Also covers the clock stepping backwards.
            _last_ms += 1
            _counter = secrets.randbelow(_COUNTER_SEED_MAX + 1)
        else:
            _counter += 1

        timestamp_ms = _last_ms
        counter = _counter

    value = timestamp_ms << 80
    value |= 0x7 << 76  # version
    value |= counter << 64
    value |= 0x2 << 62  # variant (RFC 4122)
    value |= secrets.randbits(62)

    return uuid.UUID(int=value)
