"""Auth service initial schema — users, identities, workspaces, refresh tokens.

Hand-written rather than autogenerated: the first revision of a service's
history is the one worth reading, and `citext` has to be created before the
column that uses it.

Revision ID: 0001
Revises:
Create Date: 2026-07-27
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import CITEXT, TIMESTAMP, UUID

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TIMESTAMPTZ = TIMESTAMP(timezone=True)


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    op.create_table(
        "users",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("email", CITEXT, nullable=False, unique=True),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("avatar_asset", UUID(as_uuid=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False, server_default="active"),
        sa.Column("created_at", TIMESTAMPTZ, nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", TIMESTAMPTZ, nullable=False, server_default=sa.func.now()),
        sa.Column("deleted_at", TIMESTAMPTZ, nullable=True),
        sa.Column("version", sa.Integer(), nullable=False, server_default="0"),
    )

    op.create_table(
        "external_identities",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("created_at", TIMESTAMPTZ, nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("provider", "subject", name="uq_external_identity"),
    )

    op.create_table(
        "workspaces",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", TIMESTAMPTZ, nullable=False, server_default=sa.func.now()),
    )

    op.create_table(
        "workspace_members",
        sa.Column(
            "workspace_id", UUID(as_uuid=True), sa.ForeignKey("workspaces.id"), primary_key=True
        ),
        sa.Column("user_id", UUID(as_uuid=True), sa.ForeignKey("users.id"), primary_key=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("joined_at", TIMESTAMPTZ, nullable=False, server_default=sa.func.now()),
    )

    op.create_table(
        "refresh_tokens",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        # Not in spec §4: the workspace the session was last scoped to, so a
        # refresh keeps the user where they were (see auth/models.py).
        sa.Column(
            "workspace_id", UUID(as_uuid=True), sa.ForeignKey("workspaces.id"), nullable=False
        ),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("issued_at", TIMESTAMPTZ, nullable=False, server_default=sa.func.now()),
        sa.Column("expires_at", TIMESTAMPTZ, nullable=False),
        sa.Column(
            "rotated_to", UUID(as_uuid=True), sa.ForeignKey("refresh_tokens.id"), nullable=True
        ),
        sa.Column("revoked_at", TIMESTAMPTZ, nullable=True),
    )
    # Partial index: the only refresh-token lookup by user that matters is the
    # live one — revoking every session for a user.
    op.create_index(
        "ix_refresh_user",
        "refresh_tokens",
        ["user_id"],
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    # Rotation and reuse detection both start from the presented token.
    op.create_index("ix_refresh_token_hash", "refresh_tokens", ["token_hash"], unique=True)


def downgrade() -> None:
    op.drop_table("refresh_tokens")
    op.drop_table("workspace_members")
    op.drop_table("workspaces")
    op.drop_table("external_identities")
    op.drop_table("users")
